#!/bin/bash
set -eu

. /entrypoint/functions.sh
. /entrypoint/load_env.sh

# Determine client config file
CLIENT_CONF="$PEERS_DIR/$WG_IFACE.conf"

# Wait until client config exists (generated by client-mode.sh)
if [ ! -f "$CLIENT_CONF" ]; then
    error "Client configuration not found: $CLIENT_CONF. Did client-mode.sh run?"
fi

info "🌐 Starting WireGuard interface $WG_IFACE in CLIENT mode using $CLIENT_CONF..."

# Launch WireGuard using the generated config
wg-quick up "$CLIENT_CONF"

info "🔵 Setting up client routing..."
setup_client_routing

success "✅ Client WireGuard interface $WG_IFACE is up and routing configured"
