WG_ENDPOINT=$(get_public_endpoint)
WG_MODE="server"
WG_PEER_COUNT="1"
PROXY_ENABLED="true"
PROXY_PORT_HTTP="3128"
PROXY_PORT_SOCKS5="4128"
WG_PORT="13440"
WG_IFACE="wg0"
WG_ADDRESS="10.100.0.1/24"
MASTER_PEER=""

export WG_ENDPOINT
export WG_MODE
export WG_PEER_COUNT
export PROXY_ENABLED
export PROXY_PORT_HTTP
export PROXY_PORT_SOCKS5
export WG_PORT
export WG_IFACE
export WG_ADDRESS
export MASTER_PEER