# WG_ENDPOINT=$(get_public_endpoint)
# WG_MODE="server"
# WG_PEER_COUNT="1"
# PROXY_SOCKS5_ENABLED=true
# PROXY_SOCKS5_PORT="4128"
# PROXY_SOCKS5_AUTH_ENABLED=false

# PROXY_HTTP_ENABLED=false
# PROXY_HTTP_PORT="3128"
# PROXY_HTTP_AUTH_ENABLED=false

# PROXY_CUSTOM_CONFIG=false
# WG_PORT="13440"
# WG_IFACE="wg0"
# WG_ADDRESS="10.100.0.1/24"
# MASTER_PEER=""

# export WG_ENDPOINT
# export WG_MODE
# export WG_PEER_COUNT
# export PROXY_SOCKS5_ENABLED
# export PROXY_SOCKS5_PORT
# export PROXY_SOCKS5_AUTH_ENABLED
# export PROXY_HTTP_ENABLED
# export PROXY_HTTP_PORT
# export PROXY_HTTP_AUTH_ENABLED
# export PROXY_CUSTOM_CONFIG
# export PROXY_HTTP_PORT
# export PROXY_SOCKS5_PORT
# export WG_PORT
# export WG_IFACE
# export WG_ADDRESS
# export MASTER_PEER